### ISSUE TITLE
Import already existing mods and work on them

### ISSUE THREAD

**Issue by Sceinox** [TRG-Development/Hazardous_Containment_Warfare#1]
http://www.armaholic.com/page.php?id=27918
http://www.armaholic.com/page.php?id=26687

The first mod adds gas masks and breathing sound.
The other one adds tear gas and some blinding/sound effects

I didn't check the license yet, but maybe we are allowed to use and customize them.

**Comment by TRGVoodoo** [comment]
Both of the above mentioned mods require the "Hidden Identity Pack V2", which I already wanted to use for this mod. I still have to contact the author of the mod. Since there is already a M50 Gas Mask included in this addon, we don't need the first addon. The second one would be pretty interesting! As long as it has an effect on AI, too.

**Comment by Sceinox** [comment]
> As long as it has an effect on AI, too.

Maybe I can do some tricks if gas isn't working for the AI :)

**Comment by TRGVoodoo** [comment]
would be great. hopefully we see each other on teamspeak in the next couple of days so we can have a closer look.

**Comment by Sceinox** [comment]
I'll start developing on a it at monday.
